//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjHastaneWithDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGorevliler
    {
        public byte GorevliID { get; set; }
        public string GorevliAd { get; set; }
        public string GorevliSoyad { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
    }
}
