//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjHastaneWithDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHastalar
    {
        public byte HastaID { get; set; }
        public string HastaAd { get; set; }
        public string HastaSoyad { get; set; }
        public string HastaTC { get; set; }
        public string HastaCinsiyet { get; set; }
        public string HastaDogumYeri { get; set; }
        public string HastaTelefon { get; set; }
        public string Poliklinik { get; set; }
        public string RandevuTarihi { get; set; }
    }
}
